// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type App = { id: string, name: string, icon: string, exec: Array<string>, accent: string, category: string, };
