// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[appearance]` — presentation options that sit above the per-widget `[settings]` knobs
 * (library layout now; theme/accent are planned to join it). Additive: an existing
 * config.toml without the section deserializes to the defaults below.
 */
export type Appearance = { 
/**
 * Library presentation: "rail" (XMB cascade, default) | "grid" (large poster grid)
 * | "grid-compact" (denser grid) | "list" (rows with details).
 */
layout: string, };
