// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioSink = { 
/**
 * Internal sink name (e.g. `alsa_output.pci-0000_0b_00.4.analog-stereo`) — the id
 * passed back to `audio_set_output`.
 */
name: string, 
/**
 * Human-readable label (e.g. "Built-in Audio Analog Stereo").
 */
description: string, is_default: boolean, };
