// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gpu } from "./Gpu";
import type { Tier } from "./Tier";

export type Capability = { tier: Tier, gpus: Array<Gpu>, render_nodes: Array<string>, drm_cards: Array<string>, kms_connectors: Array<string>, kms_active: boolean, vulkan_icds: Array<string>, has_real_gpu: boolean, nvidia_present: boolean, nvidia_modeset_loaded: boolean, gamescope: boolean, gamescope_session_plus: boolean, cage: boolean, diagnostics: Array<string>, };
