// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { App } from "./App";
import type { Settings } from "./Settings";

export type Config = { settings: Settings, apps: Array<App>, 
/**
 * Favorited tile ids (shown on the Home category).
 */
favorites: Array<string>, 
/**
 * Recently-launched app ids, most-recent-first (Home "recent apps").
 */
recent_apps: Array<string>, 
/**
 * Echoed back so the UI can show the user where to edit. Sent over IPC (non-empty)
 * but never written into the TOML file (empty when serializing the on-disk default).
 */
config_path?: string, 
/**
 * Set when config.toml exists but couldn't be parsed/read, so the UI can warn the user
 * ("syntax error — using defaults") instead of silently reverting. Never written to disk.
 */
config_error?: string | null, };
