// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { App } from "./App";
import type { MediaServerConfig } from "./MediaServerConfig";
import type { Settings } from "./Settings";

export type Config = { 
/**
 * Schema version of this file (see `CONFIG_VERSION`). First field: TOML needs plain
 * values emitted before tables. Absent in pre-versioning files — those deserialize to
 * the current version, correct while every shape change so far has been additive.
 */
config_version: number, settings: Settings, 
/**
 * `[media_server]` — Jellyfin browse/play integration (media_server.rs). Empty =
 * unconfigured; the jellyfin-mpv-shim pairing is adopted as a fallback at runtime.
 */
media_server: MediaServerConfig, apps: Array<App>, 
/**
 * Favorited tile ids (shown on the Home category).
 */
favorites: Array<string>, 
/**
 * Recently-launched app ids, most-recent-first (Home "recent apps").
 */
recent_apps: Array<string>, 
/**
 * Echoed back so the UI can show the user where to edit. Sent over IPC (non-empty)
 * but never written into the TOML file (empty when serializing the on-disk default).
 */
config_path?: string, 
/**
 * Set when config.toml exists but couldn't be parsed/read, so the UI can warn the user
 * ("syntax error — using defaults") instead of silently reverting. Never written to disk.
 */
config_error?: string | null, };
