// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Game = { appid: string, name: string, installdir: string, library_path: string, installed: boolean, is_tool: boolean, last_played: number, art_box: string | null, art_header: string | null, art_hero: string | null, art_logo: string | null, };
