// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Gpu = { pci: string, vendor: string, vendor_id: string, device_id: string, driver: string, class: string, };
