// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[input]` — controller/hotkey tuning (parking-lot item, NOTES-DEEPDIVE-ROADMAP.md #6).
 * Read once at startup by the gamepad and hotkey threads — changes need a relaunch (both
 * threads park in blocking waits; re-reading per event would be config I/O at 125 Hz).
 */
export type InputConfig = { 
/**
 * Guide-button long-hold threshold in ms: hold this long to close the current app
 * (short press switches). Clamped 200–5000 — below 200 every tap "closes", above 5000
 * the hold reads as broken.
 */
guide_hold_ms: bigint, 
/**
 * Grab Ctrl+Alt+Home/End inside the gamescope session (keyboard escape hatch —
 * hotkey.rs). False = no global grabs, for users whose media keyboard needs the chord.
 */
session_hotkeys: boolean, };
