// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[launch_overrides.<tile-id>]` — per-tile launch tuning (roadmap parking-lot item:
 * "per-game launch options"), hand-editable ("config is king"):
 *
 * ```toml
 * [launch_overrides."app:retroarch"]
 * env = { MANGOHUD = "1" }
 * args = ["--verbose"]
 * ```
 *
 * `env` is applied to the spawned process, `args` are appended to the tile's argv —
 * custom launchers and catalog apps only (launch_command). Steam titles don't go through
 * our spawn (`steam://rungameid` hands off to the running client), so per-game overrides
 * for them belong in Steam's own Launch Options. Threat model: a hand-edited config can
 * already put arbitrary argv in a custom launcher's `exec`, so env/args add no capability
 * it didn't have; browser (BROWSER-token) tiles still pass the same URL-only argv guard,
 * override args included.
 */
export type LaunchOverride = { 
/**
 * Extra environment for the spawned process (e.g. MANGOHUD=1, WINEESYNC=1).
 */
env: { [key in string]: string }, 
/**
 * Extra argv appended after the tile's own exec args.
 */
args: Array<string>, };
