// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Game } from "./Game";
import type { LibrarySummary } from "./LibrarySummary";

export type Library = { steam_root: string | null, games: Array<Game>, libraries: Array<LibrarySummary>, errors: Array<string>, };
