// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A still-running launched app: its process-group leader pid (each launch is its own group
 * leader via process_group(0)) plus the label/id the deck switcher shows on its card.
 */
export type LiveApp = { group: number, name: string, id?: string | null, };
