// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaItem } from "./MediaItem";
import type { MediaLibrary } from "./MediaLibrary";

export type MediaSections = { server_name: string, resume: Array<MediaItem>, latest: Array<MediaItem>, libraries: Array<MediaLibrary>, };
