// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaItem = { id: string, name: string, kind: string, overview: string | null, played_pct: number | null, runtime_mins: bigint | null, series: string | null, 
/**
 * Resume point in whole seconds (UserData.PlaybackPositionTicks). None = start from the
 * top, so "does this have a resume point" is one null-check on the frontend.
 */
position_secs: bigint | null, 
/**
 * UserData.Played — the server's fully-watched flag, for the ✓ marker on browse rows.
 */
played: boolean | null, };
