// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaInfo = { status: string, title: string, artist: string, player: string, };
