// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[media_server]` in config.toml. Empty kind/url = unconfigured (shim fallback applies).
 */
export type MediaServerConfig = { kind: string, url: string, token: string, prefer_mpv: boolean, 
/**
 * Extra mpv flags for direct-play, e.g. `["--include=~/.config/jellyfin-mpv-shim/mpv.conf"]`
 * to reuse an existing profile set (VapourSynth interpolation/denoise, keybinds).
 * When set, OmniDeck stops passing its own `--hwdec` so the config's choice rules
 * (VapourSynth filters need `hwdec=auto-copy`; a CLI `--hwdec` would override it),
 * and the auto-generated profile set below is not used.
 */
mpv_args: Array<string>, 
/**
 * Use OmniDeck's generated display-aware profile set (media_profiles.rs) when
 * `mpv_args` is empty and mpv has VapourSynth. Default true; false = bare launch.
 */
auto_profiles: boolean, };
