// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaItem = { id: string, name: string, kind: string, overview: string | null, played_pct: number | null, runtime_mins: bigint | null, series: string | null, 
/**
 * Resume point in whole seconds (UserData.PlaybackPositionTicks). None = start from the
 * top, so "does this have a resume point" is one null-check on the frontend.
 */
position_secs: bigint | null, 
/**
 * UserData.Played — the server's fully-watched flag, for the ✓ marker on browse rows.
 */
played: boolean | null, 
/**
 * BaseItemDto.IsFolder — the server's OWN answer to "is this a container". The frontend
 * used to infer that from a hard-coded `Type` allowlist, which is the wrong shape: an
 * unlisted container kind (MusicAlbum, Playlist, UserView, …) fell through as playable,
 * so Enter handed a folder id to mpv and W offered to mark a whole container watched —
 * the exact thing `toggleWatched` documents it must never do. None = the server didn't
 * say, and the frontend falls back to the name list.
 */
is_folder: boolean | null, };
