// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[media_server]` in config.toml. Empty kind/url = unconfigured (shim fallback applies).
 */
export type MediaServerConfig = { kind: string, url: string, token: string, prefer_mpv: boolean, };
