// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaItem = { id: string, name: string, kind: string, overview: string | null, played_pct: number | null, runtime_mins: bigint | null, series: string | null, 
/**
 * Resume point in seconds (from UserData.PlaybackPositionTicks; 1 tick = 100 ns).
 * None/0 = start from the beginning.
 */
position_secs: bigint | null, 
/**
 * Fully-watched flag (UserData.Played) — drives the watched checkmark + mark_unwatched.
 */
played: boolean | null, };
