// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the settings UI needs: enabled/port/running plus the QR-able pairing URL. The URL
 * carries the token in the #fragment ON PURPOSE — this command IS the pairing surface
 * (the QR the user scans); fragments are never sent over the network by browsers. It is
 * the one deliberate exception to "the webview never sees the token", mirroring how the
 * PIN of a pairing dialog must be displayable to be usable.
 */
export type RemoteStatus = { enabled: boolean, running: boolean, port: number, 
/**
 * `http://<lan-ip>:<port>/#<token>` when enabled and paired; None otherwise.
 */
url: string | null, };
