// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[remote]` in config.toml. Off by default; the token is filled on first enable.
 */
export type RemoteConfig = { 
/**
 * Master switch — nothing binds a socket while false.
 */
enabled: boolean, 
/**
 * TCP port the remote listens on (all interfaces). Non-privileged only.
 */
port: number, 
/**
 * Per-install random token (hex). Generated on first enable; blanked over IPC the
 * way media_server.token is. Clearing it here forces a new pairing on next enable.
 */
token: string, };
