// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[screensaver]` — OLED burn-in protection (roadmap Appendix C #1). The gamepad thread
 * (gamepad.rs) emits a single `idle` event after `idle_dim_secs` without pad input and
 * `active` on the next input; the frontend owns the staged presentation (dim at
 * `idle_dim_secs`, Ken-Burns pan at `ken_burns_secs`, true black at `blank_secs`) and
 * honors `enabled` — the backend always emits the transitions.
 */
export type ScreensaverConfig = { enabled: boolean, idle_dim_secs: bigint, ken_burns_secs: bigint, blank_secs: bigint, };
