// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `get_sleep_timer` returns while a timer is armed (and `set_sleep_timer` on arm).
 * `total_secs` lets the UI draw a progress ring without remembering what it asked for.
 */
export type SleepTimerStatus = { remaining_secs: number, total_secs: number, };
