// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the UI needs to render a "Update available" row/toast.
 */
export type UpdateInfo = { 
/**
 * The running version (CARGO_PKG_VERSION).
 */
current: string, 
/**
 * Latest release tag, `v` prefix stripped (e.g. "0.3.0").
 */
latest: string, 
/**
 * True when `latest` is strictly newer than `current` (numeric semver compare).
 */
update_available: boolean, 
/**
 * The release's html_url — shown as text/QR, never auto-opened.
 */
url: string, 
/**
 * Release notes body, plain text, truncated — the frontend renders it as TEXT
 * (Svelte escaping), never as HTML/markdown.
 */
notes: string, };
