#!/usr/bin/env bash
# Install OmniDeck as a selectable gamescope session in your display manager (SDDM/GDM).
#
# OmniDeck runs as a *plain* gamescope session — gamescope composites OmniDeck's window
# directly and fullscreens it. We deliberately do NOT use `gamescope-session-plus`/`--steam`
# mode: that path only displays a window it accepts as a Steam game, so a normal app like
# OmniDeck just produces a black screen (gamescope has nothing focusable to show).
#
# Requires: gamescope   (Arch: pacman -S gamescope)
#
# Usage: ./install-session.sh [/path/to/omnideck-binary]
#   (auto-detects `omnideck` in PATH or a locally built release binary)
set -euo pipefail

# --- locate the OmniDeck binary ---
BIN="${1:-}"
[ -z "$BIN" ] && BIN="$(command -v omnideck 2>/dev/null || true)"
if [ -z "$BIN" ]; then
  here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  cand="$here/src-tauri/target/release/omnideck"
  [ -x "$cand" ] && BIN="$cand"
fi
[ -n "$BIN" ] && [ -x "$BIN" ] || { echo "✗ OmniDeck binary not found. Pass it: ./install-session.sh /path/to/omnideck"; exit 1; }

command -v gamescope >/dev/null || {
  echo "✗ gamescope not found. Install it (Arch: pacman -S gamescope)."; exit 1; }

# Always install to /usr/local/share/wayland-sessions: SDDM and GDM scan it on every distro
# (it's in the default XDG_DATA_DIRS), and unlike /usr/share it stays writable on immutable
# distros (Bazzite/SteamOS), where the old "/usr/share unless read-only" heuristic silently
# failed — /usr/share/wayland-sessions exists there but is read-only, so the fallback never fired.
WAYLAND_SESSIONS=/usr/local/share/wayland-sessions
LAUNCHER=/usr/local/bin/omnideck-session

echo "Installing OmniDeck gamescope session"
echo "  binary:   $BIN"
echo "  launcher: $LAUNCHER"
echo "  session:  $WAYLAND_SESSIONS/omnideck.desktop   (needs sudo)"

sudo mkdir -p "$WAYLAND_SESSIONS" "$(dirname "$LAUNCHER")"

# Launcher: run gamescope as the session compositor, fullscreen, with OmniDeck as the
# sole client. No --steam. When OmniDeck quits, gamescope exits and you return to the
# greeter. `-f` fullscreens the app; gamescope uses the monitor's native resolution.
sudo tee "$LAUNCHER" >/dev/null <<EOF
#!/usr/bin/env bash
# OmniDeck gamescope session launcher (generated by install-session.sh).
# --force-windows-fullscreen sizes every launched app (incl. the full Brave browser, which
# otherwise opens windowed/pillarboxed) to fill the display.
# --adaptive-sync enables VRR when the display supports it (no-op otherwise).
#
# Without flags gamescope uses the display's EDID-*preferred* mode, which on many gaming
# monitors is 60 Hz even when the panel does 144/165. Put per-host overrides in
#   ~/.config/omnideck/session.conf   (sourced as bash), e.g.:
#     GAMESCOPE_FLAGS="-W 2560 -H 1440 -r 165 -O DP-3"
GAMESCOPE_FLAGS=""
CONF="\${XDG_CONFIG_HOME:-\$HOME/.config}/omnideck/session.conf"
[ -r "\$CONF" ] && . "\$CONF"
# shellcheck disable=SC2086  # word-splitting GAMESCOPE_FLAGS is the point
exec gamescope -f --force-windows-fullscreen --adaptive-sync \\
  --xwayland-count 1 --hide-cursor-delay 3000 \$GAMESCOPE_FLAGS -- "$BIN"
EOF
sudo chmod +x "$LAUNCHER"

# wayland-sessions entry — makes "OmniDeck" appear in the display-manager session list.
sudo tee "$WAYLAND_SESSIONS/omnideck.desktop" >/dev/null <<EOF
[Desktop Entry]
Name=OmniDeck
Comment=OmniDeck 10-foot media & game launcher (gamescope session)
Exec=$LAUNCHER
Type=Application
DesktopNames=gamescope
EOF

cat <<EOF

✓ Installed. Log out and pick "OmniDeck" from your display manager's session list.
  OmniDeck fullscreens itself inside gamescope; quitting it (power menu) returns you here.

Optional: force a display mode (gamescope defaults to the EDID-preferred mode — often
60 Hz on high-refresh monitors). Create ~/.config/omnideck/session.conf with e.g.:
  GAMESCOPE_FLAGS="-W 2560 -H 1440 -r 165 -O DP-3"

To remove:  sudo rm "$WAYLAND_SESSIONS/omnideck.desktop" "$LAUNCHER"
EOF
